//Daniel Lee 12/3/14 CIS 190
import java.awt.Color;
import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
public class ShoppingCart extends javax.swing.JFrame 
{
//get items from list
   public ShoppingCart() {
    
        initComponents();
        //open file and get contents
        try {           
            FileInputStream  menu = new FileInputStream("C:\\Users\\danle_000\\Documents\\java\\javaMesa\\MyShoppingCart\\MyItems.txt");
          DataInputStream data = new DataInputStream(menu);  
          BufferedReader buff = new BufferedReader(new InputStreamReader(data));
            String line;
            //declare list model for menu
            DefaultListModel listModel = new DefaultListModel();
            while((line=buff.readLine())!=null) {
                listModel.addElement(line); 
                
            }

           JLST_Menu.setModel(listModel);
          data.close(); 
        } 
        catch(IOException e){}
   //set pane color
        getContentPane().setBackground(Color.getHSBColor(40, 50, 50));
        
   }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPNL_Menu = new javax.swing.JScrollPane();
        JLST_Menu = new javax.swing.JList();
        JPNL_MyCart = new javax.swing.JScrollPane();
        JLST_MyCart = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        JLBL_Total = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dan's Digital JavaShop");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setFont(new java.awt.Font("Charlemagne Std", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/coffee-57.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Charlemagne Std", 0, 14)); // NOI18N
        jLabel2.setText("Menu");

        jLabel3.setFont(new java.awt.Font("Charlemagne Std", 0, 14)); // NOI18N
        jLabel3.setText("My Cart");

        JPNL_Menu.setToolTipText("");
        JPNL_Menu.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.lightGray));

        JLST_Menu.setBackground(new java.awt.Color(255, 102, 0));
        JLST_Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.white));
        JPNL_Menu.setViewportView(JLST_Menu);

        JLST_MyCart.setBackground(new java.awt.Color(255, 102, 0));
        JLST_MyCart.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.white));
        JPNL_MyCart.setViewportView(JLST_MyCart);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setText("Calculate Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JLBL_Total.setFont(new java.awt.Font("Charlemagne Std", 1, 18)); // NOI18N
        JLBL_Total.setText(".......");

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JPNL_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(JPNL_MyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(JLBL_Total)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPNL_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jButton2))
                            .addComponent(JPNL_MyCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLBL_Total)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//For some reason I can only modify the list if its declared outside of the method
    DefaultListModel list1 = new DefaultListModel();
    //calculate cost
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double cost =0.0;
        
        for (int i=0; i<list1.getSize();i++)
        {
           Object item= list1.getElementAt(i);
           String m = String.valueOf(item);
          
           if (m.equals("Coffee, 2.50"))
           {
           cost+= 2.5;
           }
           if (m.equals("Expresso, 2.00"))
           {
           cost+= 2.0;
           }
           if (m.equals("Hammerhead, 3.00"))
           {
           cost+= 3.0;
           }
           if (m.equals("Latte, 3.50"))
           {
           cost+= 3.5;
           }
           if (m.equals("Americano, 2.50"))
           {
           cost+= 2.5;
           }
         
        
        }
        String s = Double.toString(cost);
        JLBL_Total.setText("$"+s+"0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        list1.addElement(JLST_Menu.getSelectedValue());
        JLST_MyCart.setModel(list1);
    }//GEN-LAST:event_jButton2ActionPerformed
//remove items from cart
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        list1.removeElement(JLST_MyCart.getSelectedValue());
        JLST_MyCart.setModel(list1);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingCart().setVisible(true);
            }
        });
    }
   
    
  
    

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBL_Total;
    private javax.swing.JList JLST_Menu;
    private javax.swing.JList JLST_MyCart;
    private javax.swing.JScrollPane JPNL_Menu;
    private javax.swing.JScrollPane JPNL_MyCart;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
